favorite/urls.py
from django.urls import path
from . import views

app_name = 'favorite'

urlpatterns = [
    path('', views.show_main_favorite, name='favorite_list_view'),
    path('add-to-favorite/<int:restaurant_id>/', views.add_to_favorite, name='add_to_favorite'),
    path('list-all-restaurants/', views.list_all_restaurants, name='list_all_restaurants'),
    path('add-to-favorite-ajax/', views.add_to_favorite_ajax, name='add_to_favorite_ajax'),
    path('delete-favorite/', views.delete_favorite, name='delete_favorite'),
    path('edit/', views.edit_favorite_notes, name='edit_favorite_notes'),
    path('json/',views.show_json, name='show_json'),
    path('flutter/', views.show_main_favorite_flutter, name='show_main_favorite_flutter'),
    path('all-restaurants/flutter/', views.show_all_restaurants_flutter, name='show_all_restaurants_flutter'),
    path('add-favorite-flutter/', views.add_favorite_flutter, name='add_favorite_flutter'),
    path('delete-favorite-flutter/', views.delete_favorite_flutter, name='delete_favorite_flutter'),
    path('edit-favorite-flutter/', views.edit_favorite_flutter, name='edit_favorite_flutter'),
]

jogjappetite/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ratings/', include('ratings.urls')),   # Mengarahkan ke URLs di aplikasi 'ratings'
    path('favorite/', include('favorite.urls')),  # Mengarahkan URLs di aplikasi 'favorite'
    path('restaurant/', include('restaurant.urls')), # mengarahkan ke URLs di aplikasi 'restaurant'
    path('search/', include('search.urls')),  # Mengarahkan ke URLs di aplikasi 'search'
    path('', include('explore.urls')),  
    path('auth/', include('authentication.urls')),
]

restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('customer/', views.customer_restaurant_list, name='customer_restaurant_list'),
    path('owner/', views.owner_restaurant_list, name='owner_restaurant_list'),
    path('owner/add/', views.add_restaurant, name='add_restaurant'),
    path('owner/<int:pk>/', views.restaurant_detail, name='restaurant_detail'),
    path('owner/<int:pk>/delete/', views.delete_restaurant, name='delete_restaurant'),
    path('owner/<int:pk>/edit/', views.edit_restaurant, name='edit_restaurant'),

    path('api/get-data/', views.api_restaurant_list, name='api_restaurant_list'),
    path('api/owner/add/', views.api_add_restaurant, name='api_add_restaurant'),
    path('api/owner/<int:pk>/', views.api_restaurant_detail, name='api_restaurant_detail'),
    path('api/owner/<int:pk>/delete/', views.api_delete_restaurant, name='api_delete_restaurant'),
    path('api/owner/<int:pk>/edit/', views.api_edit_restaurant, name='api_edit_restaurant'),
]

search/urls.py
from django.urls import path, include
from search.views import *

app_name = 'search'

urlpatterns = [
    path("food-search/", food_search, name="food_search"),
    path("resto-search/", resto_search, name="resto_search"),
    path("food-search-flutter/", food_search_flutter, name="food_search_flutter"),
    path("resto-search-flutter/", resto_search_flutter, name="resto_search_flutter"),
    path('save-search/', save_search_history, name='save_search_history'),
    path('save-search-history-flutter/', save_search_history_flutter, name='save_search_history_flutter'),
    path('delete-history/<int:history_id>/', delete_search_history, name='delete_search_history'),
    path('get-search-history/', get_search_history, name='get-search-history'),
    path('get-search-history-flutter/', get_search_history_flutter, name='get_search_history_flutter'),
    path('get-random-restaurant-flutter/', get_random_restaurant_flutter, name='get_random_restaurant_flutter'), 
    path('json/', show_json, name='show_json'),
]

favorite/models.py
from django.db import models
from django.contrib.auth.models import User
from ratings.models import Restaurant

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    notes = models.TextField()  # Field untuk menyimpan alasan
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'restaurant')  # Menghindari duplikasi favorit

    def __str__(self):
        return f"{self.user.username} - {self.restaurant.nama_restoran}"

favorite/views.py
from django.shortcuts import render, get_object_or_404, redirect
from ratings.models import Restaurant
from favorite.models import Favorite
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
import json

# View untuk menampilkan daftar restoran dalam halaman favorite
from django.db.models import Avg, Count

@login_required(login_url="authentication:login")
def show_main_favorite(request):
    # Mengambil restoran yang ada di daftar favorit pengguna dengan annotasi untuk rating
    favorites = Favorite.objects.filter(user=request.user).select_related('restaurant').annotate(
        average_rating=Avg('restaurant__menu__ratings__rating'),
        rating_count=Count('restaurant__menu__ratings')
    )

    # Membuat daftar restoran beserta atribut yang diperlukan
    restaurants = [{
        'restaurant': favorite.restaurant,
        'favorite_id': favorite.id,
        'notes': favorite.notes,
        'average_rating': favorite.average_rating or 0.0,  # Jika tidak ada rating, set nilai default ke 0.0
        'rating_count': favorite.rating_count
    } for favorite in favorites]

    context = {
        'restaurants': restaurants,
    }

    return render(request, 'favorite.html', context)


@login_required(login_url="authentication:login")
def list_all_restaurants(request):
    # Mengambil semua restoran dari model Restaurant
    restaurants = Restaurant.objects.all()
    context = {
        'restaurants': restaurants,
    }
    return render(request, 'all_restaurants.html', context)

# View untuk menambahkan restoran ke favorit
@login_required(login_url="authentication:login")
def add_to_favorite(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, id=restaurant_id)

    if request.method == "POST":
        notes = request.POST.get('notes', '').strip()
        if not notes:
            return render(request, 'add_favorite_form.html', {
                'restaurant': restaurant,
                'error_message': "Please provide a note for adding this restaurant to your favorites."
            })

        # Cek apakah restoran sudah ada di daftar favorit pengguna
        if not Favorite.objects.filter(user=request.user, restaurant=restaurant).exists():
            Favorite.objects.create(user=request.user, restaurant=restaurant, notes=notes)

        return redirect('favorite:favorite_list_view')

    return render(request, 'add_favorite_form.html', {'restaurant': restaurant})

@login_required(login_url="authentication:login")
@require_POST
def add_to_favorite_ajax(request):
    import json

    # Mengambil data dari request body
    try:
        data = json.loads(request.body)
        restaurant_id = data.get('restaurant_id')
        notes = data.get('notes', '').strip()
    except json.JSONDecodeError:
        return JsonResponse({'success': False, 'message': 'Invalid JSON data.'})

    if not restaurant_id or not notes:
        return JsonResponse({'success': False, 'message': 'Restaurant ID and notes are required.'})

    restaurant = get_object_or_404(Restaurant, id=restaurant_id)

    # Cek apakah restoran sudah ada di daftar favorit pengguna
    if not Favorite.objects.filter(user=request.user, restaurant=restaurant).exists():
        Favorite.objects.create(user=request.user, restaurant=restaurant, notes=notes)
        return JsonResponse({'success': True, 'message': 'Restaurant added to favorites.', 'redirect_url': '/favorite/'})
    else:
        return JsonResponse({'success': False, 'message': 'Restaurant is already in favorites.'})
    
@login_required(login_url="authentication:login")
@require_POST
def delete_favorite(request):
    import json
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            favorite_id = data.get('favorite_id', None)

            if not favorite_id:
                return JsonResponse({'success': False, 'message': 'Favorite ID is required.'})

            # Cari berdasarkan ID favorit dan pengguna yang sedang login
            favorite = Favorite.objects.get(id=favorite_id, user=request.user)
            favorite.delete()
            return JsonResponse({'success': True})
        except Favorite.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Favorite not found.'})
        except json.JSONDecodeError:
            return JsonResponse({'success': False, 'message': 'Invalid JSON data.'})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request method.'})
    
@login_required(login_url="authentication:login")
@require_POST
def edit_favorite_notes(request):
    import json
    if request.method == "POST":
        data = json.loads(request.body)
        favorite_id = data.get('favorite_id', None)
        new_notes = data.get('notes', '').strip()

        if not favorite_id or not new_notes:
            return JsonResponse({'success': False, 'message': 'Favorite ID and new notes are required.'})

        try:
            # Cari berdasarkan ID favorit dan pengguna yang sedang login
            favorite = Favorite.objects.get(id=favorite_id, user=request.user)
            favorite.notes = new_notes
            favorite.save()
            return JsonResponse({'success': True, 'message': 'Notes updated successfully.'})
        except Favorite.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Favorite not found.'})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request method.'})
    
def show_json(request):
    # Pastikan user login
    favorites = Favorite.objects.filter(user=request.user).select_related('restaurant')
    
    # Format data agar sesuai dengan model di Flutter
    data = [
        {
            "model": "favorite.favorite",
            "pk": favorite.id,
            "fields": {
                "user": favorite.user.id,
                "restaurant": favorite.restaurant.id,
                "notes": favorite.notes,
                "created_at": favorite.created_at.isoformat()
            }
        }
        for favorite in favorites
    ]
    
    return JsonResponse(data, safe=False)

@csrf_exempt
def show_main_favorite_flutter(request):
    favorites = Favorite.objects.filter(user=request.user).select_related('restaurant')
    data = [
        {
            "id": fav.id,
            "user": fav.user.username,
            "restaurant": {
                "id": fav.restaurant.id,
                "nama_restoran": fav.restaurant.nama_restoran,
                "lokasi": fav.restaurant.lokasi,
                "average_rating": fav.restaurant.ratings_set.aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0.0,
                "gambar": fav.restaurant.gambar,
            },
            "notes": fav.notes,
            "created_at": fav.created_at,
        }
        for fav in favorites
    ]
    return JsonResponse(data, safe=False)

def show_all_restaurants_flutter(request):
    restaurants = Restaurant.objects.annotate(
        average_rating=Avg('ratings__rating')
    )
    data = [
        {
            "id": restaurant.id,
            "nama_restoran": restaurant.nama_restoran,
            "lokasi": restaurant.lokasi,
            "gambar": restaurant.gambar or "",
            "average_rating": restaurant.average_rating or 0.0,
        }
        for restaurant in restaurants
    ]
    return JsonResponse(data, safe=False)

# @login_required(login_url="authentication:login")  # Pastikan user login terlebih dahulu
@csrf_exempt
def add_favorite_flutter(request):
    if request.method == "POST":
        try:
            print(f"Request body raw: {request.body}")  # Debug tambahan
            data = json.loads(request.body)
            print(f"Request data parsed: {data}")  # Debug tambahan

            restaurant_id = data.get('restaurant_id')
            notes = data.get('notes')

            if not restaurant_id or not notes:
                return JsonResponse(
                    {"success": False, "message": "Restaurant ID and notes are required."},
                    status=400,
                )

            restaurant = get_object_or_404(Restaurant, id=restaurant_id)

            if Favorite.objects.filter(user=request.user, restaurant=restaurant).exists():
                return JsonResponse(
                    {"success": False, "message": "Restaurant already added to favorites."},
                    status=400,
                )

            Favorite.objects.create(
                user=request.user,
                restaurant=restaurant,
                notes=notes,
            )

            return JsonResponse(
                {"success": True, "message": "Favorite Restaurant Successfully added!"},
                status=201,
            )
        except json.JSONDecodeError:
            return JsonResponse(
                {"success": False, "message": "Invalid JSON data."},
                status=400,
            )
    return JsonResponse(
        {"success": False, "message": "Invalid request method."},
        status=405,
    )

@csrf_exempt
@login_required(login_url="authentication:login")  # Pastikan user login terlebih dahulu
@require_POST
def delete_favorite_flutter(request):
    try:
        # Ambil data dari body request
        data = json.loads(request.body)
        favorite_id = data.get('favorite_id', None)

        if not favorite_id:
            return JsonResponse(
                {"success": False, "message": "Favorite ID is required."},
                status=400,
            )

        # Cari favorit berdasarkan ID dan user yang sedang login
        favorite = get_object_or_404(Favorite, id=favorite_id, user=request.user)
        
        # Hapus favorit
        favorite.delete()

favorite/templates/add_favorite_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Favorite | Jogjappetite</title>
{% endblock meta %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-4">Add "{{ restaurant.nama_restoran }}" to Favorite</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-4">
            <label for="notes" class="block text-gray-700">Your Reason for Adding:</label>
            <textarea id="notes" name="notes" rows="4" class="w-full p-2 border rounded"></textarea>
            {% if error_message %}
                <p class="text-red-500">{{ error_message }}</p>
            {% endif %}
        </div>
        <div class="flex justify-between items-center mt-4">
            <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded">Submit</button>
            <a href="{% url 'favorite:list_all_restaurants' %}" class="bg-gray-500 text-white px-4 py-2 rounded">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

favorite/templates/favorite.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block meta %}
<title>Favorite | Jogjappetite</title>

<!-- CSS for header -->
<style>
    #typewriter-text {
        overflow: hidden; /* Hide the overflowing text */
        white-space: nowrap; /* Prevent line break */
        border-right: 4px solid white; /* Create cursor effect */
        animation: typing 4s steps(30, end), blink-caret 0.75s step-end infinite;
        display: block; /* Treat as block to support margin auto centering */
        width: fit-content; /* Shrink to fit content while typing */
        margin: 0 auto; /* Center align horizontally */
        max-width: 100%; /* Prevent overflow */
    }

    /* Animasi untuk mengetik */
    @keyframes typing {
        from { width: 0; }
        to { width: 100%; }
    }

    /* Animasi untuk kedipan kursor */
    @keyframes blink-caret {
        from, to { border-color: transparent; }
        50% { border-color: white; }
    }

    /* Menghilangkan kursor setelah animasi selesai */
    #typewriter-text.typing-complete {
        border-right: none; /* Remove cursor */
    }
</style>
{% endblock meta %}

{% block content %}
<div class="relative w-full bg-cover bg-center py-10" style="background-image: url('https://www.indonesia.travel/content/dam/indtravelrevamp/en/trip-ideas/Celebrate-eid-al-fitr-in-indonesia-with-these-10-delicious-food-s/headernew.jpg');">
    <h1 id="typewriter-text" class="text-3xl md:text-5xl font-bold text-white text-center">Cause every Restaurant has Memories</h1>
</div>

<section class="container mx-auto mt-6">
    <h1 class="text-md md:text-2xl font-bold mb-1 text-center">Your Favorite Restaurants</h1>
    <p class="text-center text-gray-600 mb-4">Keep track of the restaurants you love and leave the reason why</p>
    <div class="w-full flex justify-center">
        <a href="{% url 'favorite:list_all_restaurants' %}" class="bg-green-500 text-white px-4 py-2 rounded shadow-md hover:bg-green-600 transition duration-150 ease-in-out">
            Add Favorite Restaurant
        </a>
    </div>

    <div class="flex flex-wrap w-full px-3 md:px-0 gap-6 mt-6">
        {% if restaurants %}
            {% for item in restaurants %}
                <div class="w-full sm:w-1/2 md:w-[30%] lg:w-[23%] bg-white border border-gray-200 rounded-lg shadow-lg transition-transform transform hover:scale-105 dark:bg-white dark:border-slate-300 relative">
                    <!-- Tombol "X" for delete -->
                    <button onclick="openDeleteModal({{ item.favorite_id }})" class="absolute top-2 right-2">
                        <img src="{% static 'image/delete-favorite.png' %}" alt="Delete" class="w-8 h-8">
                    </button>
                    <a href="{% url 'restaurant:restaurant_detail' item.restaurant.pk %}">
                        <img class="rounded-t-lg w-full h-40 object-cover" src="{{ item.restaurant.gambar }}" alt="Restaurant Image" />
                    </a>

                    <div class="p-4 flex flex-col gap-2">
                        <a href="{% url 'restaurant:restaurant_detail' item.restaurant.pk %}">
                            <h5 class="mb-2 text-xl font-semibold text-gray-900 dark:text-dark overflow-hidden whitespace-nowrap text-ellipsis">{{ item.restaurant.nama_restoran }}</h5>
                        </a>

                        <!-- Debugging favorite ID -->

                        <div class="flex items-center justify-between -mt-3 mb-3">
                            <div class="flex items-center space-x-1 rtl:space-x-reverse">
                                {% with item.average_rating as avg_rating %}
                                {% for i in "12345"|make_list %}
                                {% if i|add:0 <= avg_rating %}
                                <svg class="w-5 h-5 text-red-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                {% else %}
                                <svg class="w-5 h-5 text-gray-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                {% endif %}
                                {% endfor %}
                                {% endwith %}
                                <p class="ml-1 text-sm font-medium text-gray-500 dark:text-gray-400">({{ item.average_rating|default:"0.0" }})</p>
                            </div>
                            <div>
                                <p class="ml-1 text-sm font-medium text-gray-500 dark:text-gray-400">{{ item.rating_count }} reviews</p>
                            </div>
                        </div>

                        <div class="flex justify-between -mt-3">
                            <span class="text-sm font-medium text-gray-500 dark:text-gray-400">{{ item.restaurant.ayce_atau_alacarte }}</span>
                            <span class="text-sm font-medium text-gray-500 dark:text-gray-400">Rp.{{ item.restaurant.harga_rata_rata_makanan|intcomma }}</span>
                        </div>
                        <p class="text-sm font-medium text-gray-500 flex items-center dark:text-gray-400 overflow-hidden whitespace-nowrap text-ellipsis">
                            {{ item.restaurant.lokasi }}</p>
                        <a href="{% url 'restaurant:restaurant_detail' item.restaurant.pk %}" class=" inline-flex items-center w-full justify-center px-3 py-2 text-sm font-medium text-center text-white bg-red-600 rounded-lg hover:bg-red-700 focus:ring-2 focus:outline-none focus:ring-red-300 dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-700">
                            Read more
                            <svg class="rtl:rotate-180 w-4 h-4 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                            </svg>
                        </a>
                        
                    </div>
                    <div class="bg-yellow-200 p-4 rounded-b-lg mt-2 flex flex-col items-center">
                        <h3 class="font-semibold text-black mb-2">My Notes</h3>
                        <p class="text-black text-center mb-2">{{ item.notes }}</p>
                        <button class="bg-gray-400 text-white px-4 py-1 rounded" onclick="openEditNotesModal({{ item.favorite_id }}, '{{ item.notes }}')">Edit</button>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <!-- Show Images if there is no Restaurant yet -->
        <div class="flex flex-col items-center justify-center py-16 w-full">
            <img src="{% static 'image/no-food.png' %}" alt="No food" class="w-56 mb-4">
            <p class="text-lg text-gray-600 text-center">There is no favorite restaurant yet.</p>
        </div>
        {% endif %}
    </div>
</section>

<!-- Modal for Deleting Favorite -->
<div id="deleteModal" class="hidden fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center">
    <div class="bg-white rounded-lg p-6 w-1/3">
        <h2 class="text-lg font-semibold mb-4">Confirm Delete</h2>
        <p>Are you sure you want to remove this restaurant from your favorites?</p>
        <div class="flex justify-end mt-6 space-x-2">
            <button id="cancelButton" class="px-4 py-2 bg-gray-300 hover:bg-gray-400 rounded">Cancel</button>
            <button id="confirmDeleteButton" class="px-4 py-2 bg-red-500 text-white hover:bg-red-600 rounded">Delete</button>
        </div>
    </div>
</div>

<!-- Modal for Editing Notes -->
<div id="editNotesModal" class="hidden fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center">
    <div class="bg-white rounded-lg p-6 w-1/3">
        <h2 class="text-lg font-semibold mb-4">Edit Notes</h2>
        <input type="text" id="newNotesInput" class="border border-gray-300 p-2 w-full mb-4 rounded" placeholder="Update your notes here...">
        <div class="flex justify-end mt-6 space-x-2">
            <button id="cancelEditButton" class="px-4 py-2 bg-gray-300 hover:bg-gray-400 rounded">Cancel</button>
            <button id="confirmEditButton" class="px-4 py-2 bg-green-500 text-white hover:bg-green-600 rounded">Save</button>
        </div>
    </div>
</div>

<!-- Animation of Header -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const textElement = document.getElementById('typewriter-text');

        // Menambahkan event listener untuk mendeteksi akhir animasi
        textElement.addEventListener('animationend', function() {
            // Menambahkan kelas untuk menghilangkan kursor
            textElement.classList.add('typing-complete');
        });
    });
</script>

<!-- Edit notes modal -->
<script>
    let favoriteIdToEdit;

    function openEditNotesModal(favoriteId, currentNotes) {
        favoriteIdToEdit = favoriteId;
        document.getElementById('newNotesInput').value = currentNotes;
        document.getElementById('editNotesModal').classList.remove('hidden');
    }

    document.getElementById('cancelEditButton').addEventListener('click', function () {
        document.getElementById('editNotesModal').classList.add('hidden');
    });

    document.getElementById('confirmEditButton').addEventListener('click', function () {
        editFavoriteNotes(favoriteIdToEdit);
        document.getElementById('editNotesModal').classList.add('hidden');
    });

    function editFavoriteNotes(favoriteId) {
        const newNotes = document.getElementById('newNotesInput').value;
        fetch("{% url 'favorite:edit_favorite_notes' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: JSON.stringify({ 'favorite_id': favoriteId, 'notes': newNotes }),
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                location.reload();
            } else {
                alert(data.message);
            }
        });
    }
</script>

<!-- Delete Restaurant from Favorite list -->
<script>
    let favoriteIdToDelete;

function openDeleteModal(favoriteId) {
    console.log('Favorite ID to delete:', favoriteId); // Tambahkan ini untuk debugging
    favoriteIdToDelete = favoriteId;
    document.getElementById('deleteModal').classList.remove('hidden');
}

document.getElementById('cancelButton').addEventListener('click', function () {
    document.getElementById('deleteModal').classList.add('hidden');
});

document.getElementById('confirmDeleteButton').addEventListener('click', function () {
    deleteFavorite(favoriteIdToDelete);
    document.getElementById('deleteModal').classList.add('hidden');
});

function deleteFavorite(favoriteId) {
    console.log('Deleting favorite with ID:', favoriteId); // Tambahkan ini untuk debugging
    fetch("{% url 'favorite:delete_favorite' %}", {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}',
        },
        body: JSON.stringify({ 'favorite_id': favoriteId }),
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            location.reload();
        } else {
            alert(data.message);
        }
    });
}
</script>

{% endblock %}